package monami.lms.utilities;

public enum CustomerStatus {
	INITIATED, 
	OTP_GENERATED_BEFORE_ACTIVATION, 
	OTP_VERIFIED_BEFORE_ACTIVATION, 
	ACTIVE, 
	OTP_GENERATED_AFTER_ACTIVATION, 
	OTP_VERIFIED_AFTER_ACTIVATION,
	SUSPENDED,
	BLOCKED
}
